name: Test PR

on:
  push:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-flake8
        python -m pip install pytest-pydocstyle
        python -m pip install pytest-cov
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest -v
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: List files
      run: |
        pwd
        ls -lah